name: mirror

on:
  push:
    branches:
      - "main"

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/G-EIP-700-PAR-7-1-eip-hugo.raygade.git"

jobs:
  push_to_mirror:
    name: "Mirror repository"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
